FROM golang:1.25

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/*

COPY . .

RUN go mod download

CMD ["go", "test", "-tags", "no_web", "./..."]
